### PR TITLE
Update pinning

### PR DESCRIPTION
**Pull request by croth1**
supersedes #7

### CODE REVIEW

**Comment by croth1** [comment]
depends on https://github.com/conda-forge/pango-feedstock/pull/19

**Comment by croth1** [comment]
also https://github.com/conda-forge/atk-feedstock/pull/8

**Comment by croth1** [comment]
@conda-forge/gtk2, @ocefpaf,  I am puzzled here:

In travis I get following error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - glib=2.58
  - pango=1.40 -> harfbuzz[version='>=1.9.0,<2.0a0'] -> glib[version='>=2.56.2,<2.57.0a0']
```

But I rebuilt both harfbuzz (https://github.com/conda-forge/harfbuzz-feedstock/pull/39) and pango (https://github.com/conda-forge/pango-feedstock/pull/19). So there should be versions that satisfy the glib requirements. Why does the solver still complain?

 Is it because the solver cannot choose the latest harfbuzz for a different pin inconsistency?

**Comment by pkgw** [comment]
Yes, in order for this to work, we'll need to update the harfbuzz pin from 1 to 2, [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L342-L343), and then rerender.

[The ABI Lab report](https://abi-laboratory.pro/?view=timeline&l=harfbuzz) shows that some symbols were dropped in the transition to the 2.x series, but that releases since 2.0 have maintained compatibility. So I think it is safe to update the pin.

@croth1 would you be interested in filing a PR to conda-forge-pinning-feedstock to propose this change? [Here is a recent PR](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/171) you could use as a template.

**Comment by croth1** [comment]
@pkgw, I don't have time right now, but I'll be able to do it later this week :+1:

**Comment by pkgw** [comment]
`harfbuzz` pin has been updated and is propagating; I think this should work now. (Might need to be rerun if this CI runs before the latest `pango` package gets uploaded.)

**Pull request merged**
